### ISSUE TITLE
Ошибки в описании функций.

### ISSUE THREAD

**Issue by nazbav** [Ganzal/php-pinger-service#1]
1. Имеются ошибки в описании функций.
2. Обработчик Ganzal\Lulz\Pinger\Assets\Exceptions\PID_Unlink_Fail_Exception отсутствует.
3. В PingerConsole.php ошибки в функции sprintf() (ошибки написания);
еще шторм орет с PingWorker
Проверенно в PHPStorm 2016.3.3

![image](https://user-images.githubusercontent.com/21163205/29227076-15e74c26-7edd-11e7-9a5f-4dbf1afe064f.png)
![image](https://user-images.githubusercontent.com/21163205/29227367-3e3d7960-7ede-11e7-83f6-21c4a378b2bc.png)

**Comment by Ganzal** [comment]
Спасибо за информацию!

Я с год назад уже какие-то ошибки поисправлял, просто не пушил на гитхаб. Перепроверю на всякий случай еще раз.

**Comment by nazbav** [comment]
Хорошо)
